plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('build') {
    dependsOn ':buildFrontendAndCopyOutputToBackend'
}

tasks.named('bootRun') {
    dependsOn ':buildFrontendAndCopyOutputToBackend'
    def runtimeDirectory = rootProject.layout.buildDirectory.dir('runtime')
    workingDir runtimeDirectory
    doFirst {
        runtimeDirectory.get().asFile.mkdirs()
    }
}
